name: ios

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 23 * * *'

jobs:
  check-framework-version:
    runs-on: macos
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies in Gemfile
        run: bundle install

      - name: Set up ENV variables and .env file for cocoapods-keys
        run: |
          git clone git@github.com:WW-Digital/ios-common-config.git
          touch .bash_env
          export BASH_ENV="$GITHUB_WORKSPACE/.bash_env"
          bash ./ios-common-config/circleci/fetch-keys.sh WWMobile .
        env:
          TRIGGER_OIDC_CURL_USER: ${{ secrets.TRIGGER_OIDC_CURL_USER }}
          TRIGGER_OIDC_CURL_PASSWORD: ${{ secrets.TRIGGER_OIDC_CURL_PASSWORD }}
          TRIGGER_OIDC_CURL_SERVICE_ACCOUNT: ${{ secrets.TRIGGER_OIDC_CURL_SERVICE_ACCOUNT }}

      - name: Check framework version
        run: |
          source "$GITHUB_WORKSPACE/.bash_env"
          bundle exec fastlane check_xcframework_version
